version: '3.8'

services:
  app:
    build: .
    container_name: multi_model_app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./temp:/app/temp
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      # Override or add additional environment variables here if needed
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
      - KMP_DUPLICATE_LIB_OK=${KMP_DUPLICATE_LIB_OK}
      - MONGODB_URL=${MONGODB_URL}